version: "3.8"
services:
    postgres:
        image: postgres
        environment:
            - "POSTGRES_PASSWORD=password"
        volumes:
            - "./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    app:
        build: .
        image: pfun-fastapi-todo:0.0.2
        ports:
            - "8000:80"
        volumes:
            - ".:/var/todo-app"
        depends_on:
            - postgres
